<a href="https://colab.research.google.com/github/Jaron-Sauerwein/DS210/blob/main/Bottle_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
bt = pd.read_csv('bottles.csv')

In [ ]:
def find_iqr_outliers(bt, column):
  Q1 = bt[column].quantile(0.25)
  Q3 = bt[column].quantile(0.75)
  IQR = Q3 - Q1
  lower_bound = Q1 - 1.5 * IQR
  upper_bound = Q3 + 1.5 * IQR
  outliers = bt[(bt[column] < lower_bound) | (bt[column] > upper_bound)]
  return outliers, lower_bound, upper_bound

In [ ]:
outliers, lower_bound, upper_bound = find_iqr_outliers(bt, 'Salnty')

print(f"Lower Bound: {lower_bound}")
print(f"Upper Bound: {upper_bound}")
print(f"Total Outliers Found: {len(outliers)}\n")

outliers

Lower Bound: 32.376
Upper Bound: 35.294000000000004
Total Outliers Found: 4

     Unnamed: 0  Depthm  T_degC    Salnty  O2ml_L    STheta
146      668842      11  15.150  31.61900   5.700  23.33600
157       55504      20  17.770  32.29800   5.770  23.26100
200      894687       0  17.322  24.42177   7.165  24.42177
500      474872      10  16.770  35.67000     NaN  26.08500

In [ ]:
outliers, lower_bound, upper_bound = find_iqr_outliers(bt, 'Depthm')

print(f"Lower Bound: {lower_bound}")
print(f"Upper Bound: {upper_bound}")
print(f"Total Outliers Found: {len(outliers)}\n")

outliers

Lower Bound: -347.5
Upper Bound: 688.5
Total Outliers Found: 66

     Unnamed: 0  Depthm  T_degC   Salnty  O2ml_L   STheta
20       870262     739   5.447  34.3813   0.122  27.1473
36       361228     808   4.460  34.4110   0.590  27.2760
37       626567     800   4.460  34.4250     NaN  27.2860
40        85197    1000   4.100  34.5240   0.570  27.4050
66        87504     826   5.240      NaN   0.270      NaN
..          ...     ...     ...      ...     ...      ...
933       26449     900   4.200  34.5200   0.630  27.3910
964        3209    1085   3.620  34.3800   0.870  27.3390
965       19740     700   5.040  34.3940     NaN  27.1970
976      343963     900   4.360  34.4440   0.300  27.3130
987      294312    1300   3.250  34.5950   0.870  27.5470

[66 rows x 6 columns]

In [ ]:
outliers, lower_bound, upper_bound = find_iqr_outliers(bt, 'T_degC')

print(f"Lower Bound: {lower_bound}")
print(f"Upper Bound: {upper_bound}")
print(f"Total Outliers Found: {len(outliers)}\n")

outliers

Lower Bound: -2.147500000000001
Upper Bound: 23.6325
Total Outliers Found: 1

     Unnamed: 0  Depthm  T_degC  Salnty  O2ml_L  STheta
758      203385      10   24.18   34.92    5.07   23.53

In [ ]:
outliers, lower_bound, upper_bound = find_iqr_outliers(bt, 'O2ml_L')

print(f"Lower Bound: {lower_bound}")
print(f"Upper Bound: {upper_bound}")
print(f"Total Outliers Found: {len(outliers)}\n")

outliers

Lower Bound: -5.29075
Upper Bound: 11.95125
Total Outliers Found: 0

Empty DataFrame
Columns: [Unnamed: 0, Depthm, T_degC, Salnty, O2ml_L, STheta]
Index: []

In [ ]:
outliers, lower_bound, upper_bound = find_iqr_outliers(bt, 'STheta')

print(f"Lower Bound: {lower_bound}")
print(f"Upper Bound: {upper_bound}")
print(f"Total Outliers Found: {len(outliers)}\n")

outliers

Lower Bound: 22.422124999999998
Upper Bound: 29.209125000000004
Total Outliers Found: 0

Empty DataFrame
Columns: [Unnamed: 0, Depthm, T_degC, Salnty, O2ml_L, STheta]
Index: []

In [ ]:
num_cols = ['Depthm', 'T_degC', 'Salnty', 'O2ml_L', 'STheta']

bt_cleaner = bt.copy()

for col in num_cols:
    Q1 = bt_cleaner[col].quantile(0.25)
    Q3 = bt_cleaner[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    bt_cleaner = bt_cleaner[(bt_cleaner[col] >= lower) & (bt_cleaner[col] <= upper) | bt_cleaner[col].isna()]

print(f"Original rows: {len(bt)}")
print(f"Rows remaining after outliers removed: {len(bt_cleaner)}")

Original rows: 1000
Rows remaining after outliers removed: 929

In [ ]:
missing_total = bt_cleaner.isna().sum().sum()
print(f"Total values missing: {missing_total}")

Total values missing: 301

In [ ]:
bt_clean = bt_cleaner.dropna()
print("Check for missing values:", bt_clean.isna().sum().sum())

Check for missing values: 0

In [ ]:
from google.colab import files
bt_clean.to_csv('clean_bottles.csv', index=False)
files.download('clean_bottles.csv')